# Default values for ipn-fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.devops.rivtower.com/xiangjiandao/social-app-admin

  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: rivtower-docker-registry

nameOverride: ""
fullnameOverride: ""
configMapEnabled: true

service:
  type: ClusterIP
  port: 80

env:
  product_tenant: "social-app-admin"
  envName: ""

app:
  config:
    enabled: true
    configMapData: |
      {}

ingress:
  enabled: true
  className: 'rivdap'
  annotations: {}
  hosts:
    - host: "xiangjiandao-admin.rivtower.xyz"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 4000m
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
