apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipn-fe.fullname" . }}
  labels:
    app: {{ include "ipn-fe.name" . }}
    chart: {{ include "ipn-fe.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.env.envName }}
    env: {{ .Values.env.envName }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "ipn-fe.name" . }}
    release: {{ .Release.Name }}
